### ISSUE TITLE
Can widgy be used without Mezzanine?

### ISSUE THREAD

**Issue by WoLpH** [fusionbox/django-widgy#323]
As #220 already tells, the `WIDGY_MEZZANINE_SITE` setting is required. But even beyond that, I get import errors when trying to use Widgy:

```
Internal Server Error: /admin/page_builder/callout/1/
Traceback (most recent call last):
  File "django/core/handlers/base.py", line 199, in get_response
    response = middleware_method(request, response)
  File "debug_toolbar/middleware.py", line 114, in process_response
    toolbar_content = toolbar.render_toolbar()
  File "debug_toolbar/toolbar.py", line 67, in render_toolbar
    return render_to_string('debug_toolbar/base.html', context)
  File "django/template/loader.py", line 164, in render_to_string
    return t.render(Context(dictionary))
  File "django/template/base.py", line 140, in render
    return self._render(context)
  File "django/test/utils.py", line 85, in instrumented_test_render
    return self.nodelist.render(context)
  File "django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "django/template/defaulttags.py", line 433, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=context.current_app)
  File "django/core/urlresolvers.py", line 503, in reverse
    app_list = resolver.app_dict[ns]
  File "django/core/urlresolvers.py", line 329, in app_dict
    self._populate()
  File "django/core/urlresolvers.py", line 290, in _populate
    for name in pattern.reverse_dict:
  File "django/core/urlresolvers.py", line 315, in reverse_dict
    self._populate()
  File "django/core/urlresolvers.py", line 303, in _populate
    lookups.appendlist(pattern.callback, (bits, p_pattern, pattern.default_args))
  File "django/core/urlresolvers.py", line 230, in callback
    self._callback = get_callable(self._callback_str)
  File "django/utils/functional.py", line 32, in wrapper
    result = func(*args)
  File "django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "widgy/contrib/widgy_mezzanine/views.py", line 22, in <module>
    from mezzanine.pages.views import page as page_view
ImportError: No module named mezzanine.pages.views
```

**Comment by rockymeza** [comment]
Hi,

Widgy can be used without mezzanine, but I definitely think we're missing
some docs on it.

Do you have widgy.contrib.widgy_mezzanine installed? I think if you remove
it, you should be good.

-Rocky Meza
2015年5月22日 下午5:54于 "Rick van Hattem" <notifications@github.com>写道：

**Comment by WoLpH** [comment]
Guess I should have mentioned the installed packages, my bad :)

I've just removed all installed packages (besides our normal list) and simply installed `django-widgy[page_builder]`, which installed the following list:
```
beautifulsoup4==4.3.2
bleach==1.4.1
django-appconf==1.0.1
django-argonauts==1.1.1
django-compressor==1.5
django-pyscss==2.0.2
django-treebeard==3.0
django-widgy==0.6.1
enum34==1.0.4
html5lib==0.99999
Markdown==2.6.2
pathlib==1.0.1
pyScss==1.3.4
sorl-thumbnail==12.2
Unidecode==0.4.17
```

The stacktrace remains the same however. The only thing I get when doing a `pip freeze | grep -i widgy` is `django-widgy==0.6.1`

**Comment by WoLpH** [comment]
I should note that there is a `widgy_mezzanine` directory in the widgy contrib directory. So I guess it is installed, but that appears to be part of the widgy base package.

**Comment by WoLpH** [comment]
Nevermind... it appears to be due to copy/pasting with the missing docs. I'll add a pull request for better docs soon :)
